# Generated by Django 2.1.1 on 2018-09-30 20:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате 9999999999', regex='^\\d{10}$')])),
                ('passport_number', models.CharField(max_length=25)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('loan_type', models.CharField(choices=[('cash', 'cash'), ('home', 'home'), ('auto', 'auto')], default='cash', max_length=4)),
                ('min_rating', models.PositiveIntegerField(default=0)),
                ('max_rating', models.PositiveIntegerField(default=0)),
                ('rotation_began_at', models.DateTimeField(blank=True, null=True)),
                ('rotation_ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'new'), ('sent', 'sent'), ('received', 'received'), ('approved', 'approved'), ('denied', 'denied'), ('issued', 'issued')], default='new', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='core.Form')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='core.Offer')),
            ],
        ),
    ]
